version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
      - ELASTIC_PASSWORD=yourpassword # Replace with a strong password
    ports:
      - "9200:9200" # HTTP port
      - "9300:9300" # TCP port for cluster communication
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=yourpassword # Use the same password as above
    ports:
      - "5601:5601" # Kibana port
    networks:
      - es-net

volumes:
  esdata1:
    driver: local

networks:
  es-net:
    driver: bridge
